### ISSUE TITLE
Retour sur ville/mauguio

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#107]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/mauguio :

Hello , merci pour la correction sur Mauguio! Je m'occupe de la com pour l'association Vélo Pays de l'Or et vais faire passer votre tableau  de suite. 
Me joindre : Evelyne : velopaysdelor@gmail.com

**Comment by mquandalle** [comment]
#75
