### ISSUE TITLE
Modifier l'identifiant utilisé pour les EPCI

### ISSUE THREAD

**Issue by guillett** [mquandalle/mesaidesvelo#110]
Pour le moment les EPCI sont définies via leur nom tel qu'il apparaît dans les documents de référence.

Hélas, par exemple, `CA Agglo Pays d’Issoire` est utilisé alors que cet EPCI apparaît `CA Agglo Pays d'Issoire` c'est à dire avec `'` et pas `’`. Cela ne posait pas de problème en 1.1.2 mais avec la 2.0.0 ça ne fonctionne plus.

```js
  var aides = aidesVelo({
    "vélo . type": "électrique",
    "localisation . epci": "CA Agglo Pays d'Issoire",
    "localisation . département": "68",
    "localisation . région": "44",
  })

  console.log(aides)
```
Renvoie 
```js
[
  {
    title: 'Bonus vélo électrique de l’État',
    description: 'Le Bonus vélo versé par l’État complète l’aide versée par une collectivité\n' +
      'territoriale. Votre revenu fiscal de référence par part doit être inférieur\n' +
      'à 13 489 € pour en bénéficier. Le montant de l’aide est identique au montant\n' +
      'accordé par la collectivité dans la limite de 200€.\n',
    url: 'https://www.service-public.fr/particuliers/vosdroits/F35475',
    amount: 150,
    collectivity: { kind: 'pays', value: 'France' }
  },
  {
    title: "Agglo Pays D'Issoire",
    description: undefined,
    url: 'http://www.mairie-egliseneuvedesliards.fr/fileadmin/Mairie_Egliseneuve-des-Liards/2-Documents/pdf/Prime-VAE_Formulaire-demande1309.pdf',
    amount: 150,
    collectivity: { kind: 'epci', value: 'CA Agglo Pays d’Issoire' }
  }
]
```

en 1.2.2
mais une liste vide v2.

C'est peut-être le moment de passer par les codes SIREN ?

**Comment by mquandalle** [comment]
Pardon j'ai pas bien documenté, en v2 il faut fournir le SIREN de l'EPCI

**Comment by guillett** [comment]
Oui désolé j'allais venir fermer cette issue. Merci beaucoup. L'histoire des apostrophes valait comme même le coup d'être partagée :sweat_smile: . Merci !

**Comment by mquandalle** [comment]
Sur l'histoire des apostrophes https://github.com/betagouv/publicodes/issues/106
