### ISSUE TITLE
Code postal Nantes

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#116]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/nantes :

Bonjour,
Super votre site ! Je l'ai découvert grâce à un article des Echos Start.
Il y a un peu plus d'aides sur Nantes métropole que ce que vous indiquez, notamment pour les pros. Sinon, pour le code postal vous devriez mettre 44000 plutôt que 44100 qui est un sous-code postal de la ville.
URL des aides pros possibles : https://metropole.nantes.fr/aide-achat-velo-pro#serviceTocEntry0
Bonne fin de journée,
Ingrid Baudry
Conseil en communication
www.basileo.fr

**Comment by mquandalle** [comment]
Pour les aides pros, cf. #135
