### ISSUE TITLE
Aide pour des accessoires vélo

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#119]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/etampes :

La ville d'Étampes attribué jusqu'à 100 euros d'aide à l'achat d'accessoires liés à l'achat d'un vélo électrique ou classique.
Joël nolleau délégué du maire pour l'environnement

**Comment by mquandalle** [comment]
Je ne trouve pas de référence concernant cette aide.

**Comment by jmquandalle** [comment]
https://www.mairie-etampes.fr/wp-content/uploads/2022/01/1241-Etampes-info.pdf

voir page 2 du pdf "Etampes Info" de 2022 le titre : "CYCLISTES : PROFITEZ DE L’AIDE MUNICIPALE
DE MATÉRIEL POUR ÉQUIPER VOTRE VÉLO "

**Comment by mquandalle** [comment]
Ok donc c'est une aide spécifiquement pour du matériel type casque ou antivol, c'est pas encore géré par le site.
