### ISSUE TITLE
Cumul des aides supérieur au prix du vélo

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#121]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/montpellier :

Bonjour,

A Montpellier, quand le prix du vélo est à 1000 €, le revenu inférieur à 1124 €, le total des aides est de 1150 €. Supérieur au prix du vélo ! Bug ?! Merci de me contacter pour discuter partenariat, Kim Vu Dinh

**Comment by mquandalle** [comment]
À creuser, mais il me semble effectivement qu'avec le cumul des aides de la métropole, du département, de la région et de l'état, le cumul des aides peut être supérieur au montant du vélo.
