### ISSUE TITLE
Retour sur mentions-legales

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#125]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/mentions-legales :

Bonjour, 

Je me présente je suis Paul Durville, je suis en charge des relation presse pour la marque de cycles SPECIALIZED. 

J’ai récemment découvert votre site via un article sur le site des Echos. 
J’aimerais voir avec vous la possibilité de proposer à nos magasins revendeurs d’intégrer MesAidesVélo sur leur site internet.

Avant de communiquer sur votre site je voulais échanger avec vous à ce sujet et avoir un retour de votre part. 

En attendant votre retour je reste à votre disposition si jamais vous avez des questions.
Bien à vous
Paul Durville

**Comment by mquandalle** [comment]
Bonjour je n'ai pas vos coordonnées pour vous recontacter, vous pouvez m'écrire à maxime [at] mesaidesvelo.fr

**Comment by jmquandalle** [comment]
J'ai laissé un message sur le site specialized à l'attention de Paul Durville, pur qu'il te contacte sur l'email fourni 
https://www.specialized.com/fr/fr/contact-us
