### ISSUE TITLE
Outre-mer

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#127]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ :

Bonjour,
Un site super ... si vous ne nous aviez pas oublié, nous les français d'outre-mer. Dommage.

**Comment by mquandalle** [comment]
- Guadeloupe : pas d'aide
- Martinique : pas d'aide
- Mayotte 
    - Cadema mais je ne trouve pas le détail [source](https://lejournaldemayotte.yt/2021/12/22/la-cadema-encourage-la-mobilite-douce-avec-la-prime-a-velo/)
- Nouvelle Calédonie : Franc Pacifique non géré sur le site
- Plonésie française : France Pacifique non géré sur le site
    - Aide à Papeete toujours d'actualité ? [source](http://www.ville-papeete.pf/articles.php?id=2722)
- La Réunion : pas d'aide [source](https://www.linfo.re/la-reunion/societe/bonus-velo-aucune-aide-a-la-reunion)
