### ISSUE TITLE
Retour sur integrer-sur-mon-site

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#131]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/integrer-sur-mon-site :

Integration des iframe

Mettre un titre + Taille de la fenêtre iframe pour une meilleure intégration 

voir par exemple l'utilisation sur les sites : 
https://www.ovelo.fr/fr/content/7-prime-velo-electrique
https://v17.minimx.fr/fr/

**Comment by mquandalle** [comment]
J'ai corrigé l'auto-redimensionnement normalement (c'est un peu difficile à tester).

Ça ne corrige pas le problème sur les deux sites qui utilisent l'intégration car ils passent directement par une iframe de la mauvaise hauteur plutôt que par le script fourni (voir les sources des pages).
