### ISSUE TITLE
Lien non valide sur certaines aides

### ISSUE THREAD

**Issue by Kout95** [mquandalle/mesaidesvelo#139]
Les liens invalides détectés via le package aides-velos sur aides jeunes : 
Angers :
- https://www.angersloiremetropole.fr/mon-quotidien/mobilites/velo/velo-a-assistance-electrique/index.html

Rochefort :
`https://www.agglo-rochefortocean.fr/velo-assistance-electrique-velos-pliants-cargos-aide-lacquisitionhttps://www.agglo-rochefortocean.fr/velo-assistance-electrique-velos-pliants-cargos-aide-lacquisition` 
=>
`https://www.agglo-rochefortocean.fr/velo-assistance-electrique-velos-pliants-cargos-aide-lacquisition`

Nevers :
https://www.agglo-nevers.net/wp-content/uploads/2021/01/RTHglement-attribution-subvention-2021-1.pdf

Pau:
https://www.pau.fr/article/retour-sur-la-premiere-session-daide-a-lachat-velos

Loir-et-Cher :
http://www.mer41.fr/Coup-de-pouce-pour-les-velos-electriques

Grentheville (serveur de la ville indisponible): 
https://grentheville.fr/index.php/component/content/article/90-informations-communales/200-aide-a-l-achat-d-un-velo-electrique-neuf

**Comment by mquandalle** [comment]
Merci, je vais corriger.

Hélas, j'avais déjà remarqué que ces liens ont une tendance à périmer rapidement...

Une solution pour mitiger ce problème pourrait être de faire un bot qui contrôle régulièrement la validité des liens. Ça peut se faire facilement avec une Github action et un script qui vérifie a minima les erreurs 404.
