### ISSUE TITLE
Nouveau lien aide côte d'or

### ISSUE THREAD

**Issue by AntoineAugusti** [mquandalle/mesaidesvelo#146]
L'ancien lien ne fonctionne plus

https://www.cotedor.fr/aide/acquisition-de-velo-assistance-electrique

Désolé ne pas faire la PR moi-même je suis sur mobile.

**Comment by mquandalle** [comment]
Merci Antoine !
J'ai essayé plusieurs fois hier et aujourd'hui encore de charger le site https://www.cotedor.fr mais ça ne fonctionne pas. C'est seulement pour moi ou le site est cassé ?

**Comment by AntoineAugusti** [comment]
@mquandalle Bien accessible chez moi (mais en Côte-d'Or) à l'instant.
