### ISSUE TITLE
Ajouts d'aides de collectivités

### ISSUE THREAD

**Issue by guillett** [mquandalle/mesaidesvelo#168]
En vrac :
https://mes-aides.pole-emploi.fr/communaute-de-communes-ile-d-oieron/aide-a-l-achat-d-un-velo-a-assistance-electriquevae-
https://mes-aides.pole-emploi.fr/departement-eure/aide-departementale-a-l-achat-de-velo-electrique
https://mes-aides.pole-emploi.fr/pays-basque-adour/subvention-pour-velo-assistance-electrique
https://mes-aides.pole-emploi.fr/communaute-de-communes-grand-orb/subvention-velo-electrique
https://mes-aides.pole-emploi.fr/communaute-de-communes-du-pays-d-aix/un-ecocheque-pour-le-velo-electrique

De mes recherches via `git log -p src/aides.yaml | grep XXX` ces aides n'ont pas été ajoutées historiquement dans le passé et je ne les vois pas actuellement.

**Comment by mquandalle** [comment]
- **Communauté de communes Île d'OIéron**
  plus dispo en 2022 ?
- **Département Eure**
  prêt à taux zéro, pas géré sur mesaidesvélo
- 👍 **Pays Basque - Adour**
  J'ai l'impression qu'il y a eu un regroupement / une modification de l'organisme en charge des transports.
  Nouveau site : https://www.txiktxak.fr/vos-moyens-de-transport-a-la-carte/aide-a-l-achat-velo/
  L'aide est intégrée de notre côté avec le libellé « Agglomération Pays Basque » https://mesaidesvelo.fr/ville/bayonne?velo=%C3%A9lectrique
- 👍 **Grand Orb** 
  aide reconduite en 2022, à intégrer https://www.grandorb.fr/Developpement-durable/Mobilite/5/3733.html
- 👍 **Métropole Aix Marseillle Provence**
  à intégrer https://www.agglo-paysdaix.fr/transports/le-velo-a-assistance-electrique/particuliers.html

**Comment by guillett** [comment]
Désolé pour le flux mal qualifié. Merci pour les analyses et les détails partagés. :pray:

**Comment by guillett** [comment]
En fait pour le pays basque, il y a un doublon de leur côté, d'où la confusion :
https://mes-aides.pole-emploi.fr/pays-basque-adour/subvention-pour-velo-assistance-electrique
https://mes-aides.pole-emploi.fr/pays-basque-adour/subvention-pour-l-acquisition-d-un-velo-electrique

**Comment by mquandalle** [comment]
Et pour Aix, l'aide est épuisée et plus disponible
