### ISSUE TITLE
Aides non réinitialisées lors du changement de commune 

### ISSUE THREAD

**Issue by jmquandalle** [mquandalle/mesaidesvelo#189]
Lorsqu'on change de commune en tapant dans la zone localisation après avoir sélectionné une commune, les aides affichées restent sur la commune initiale.
sur l'exemple ci-dessous : sélection de 78600 - Visualisation des aides VAE - Changement de commune avec 75000 => pas d'affichage de l'aide Ville de Paris
![image](https://user-images.githubusercontent.com/2477841/187648062-dfa017cf-44de-4dcf-a9f4-6c6b9eb11266.png)
Pour que ce soit pris en compte il faut ne pas saisir directement une commune, mais d'abord cliquer sur la croix dans la zone localisation, puis saisir la commune

**Comment by mquandalle** [comment]
Lié à https://github.com/sveltejs/kit/issues/6459
