### ISSUE TITLE
Difficulté d'installation du repo

### ISSUE THREAD

**Issue by Tumulte** [mquandalle/mesaidesvelo#202]
J'ai essayé d'installer le dépôt aides vélo et j'ai rencontré quelques erreurs au `npm i`

* les fichiers suivants sont indiqués comme manquants : `miniatures.json`, `gsheet-forfait.json` et `gsheet-blacklist`
* il y a une erreur avec le module `@etalab/decoupage-administratif`, il faut node > 17 pour avoir le support de l'export d'un .json. Ça peut valoir le coup d'indiquer la version minimale de node dans le `package.json`

Merci et je suis dispo pour des précisions

**Comment by mquandalle** [comment]
Chez moi l'installation du paquet fonctionne (node v16) :

```sh
mkdir /tmp/test-aides-velo
cd /tmp/test-aides-velo
npm init -y
npm install aides-velo
echo "import aidesVelo from 'aides-velo'; console.log(aidesVelo());" >> test.mjs
node test.mjs
```

C'est la raison pour laquelle je te demande une reproduction minimale que je peux “git clone” pour identifier le problème.

**Comment by Tumulte** [comment]
je parle du repo mesaidesvelo, pas du module! Si on le clone et qu'on fait une install fraiche on rencontre les problèmes ci-dessus

**Comment by mquandalle** [comment]
Ah ok c'est pour ça que je ne comprenais pas.

Pour les miniatures le dépôt contient un sous-module git. Il faut utiliser `--recursive` lors du clone:

> git clone --recursive git@github.com:mquandalle/mesaidesvelo.git

Les fichiers `gsheet-forfait.json` et `gsheet-blacklist` sont extrait d'un Google sheet sur lequel il faut une clé d'API privé pour y accéder, mais normalement ces fichiers ne sont pas requis pour lancer le site, ils sont seulement utilisés pour la page sur le forfait mobilité durable.

Pour la version de node, pas besoin de node 17+, ça fonctionne en node 16, y compris avec l'import de JSON
