### ISSUE TITLE
Problème avec le index.ts dans le package-aides-velo

### ISSUE THREAD

**Issue by Tumulte** [mquandalle/mesaidesvelo#203]
Le dossier `package-aides-velo` contient le fichier `index.ts` à la racine et ça pose un poblème lorsque l'on compile un projet avec `ts-node`.

En gros, si on compile un projets avec le module `package-aides-velo` en utilisant `ts-node`, ce dernier va ignorer les règles d'export du `package.json` (qui pointent vers `build/index.*`), tenter de compiler le `index.ts` et planter.

Il suffit de déplacer les sources hors de la racine (dans un dossier `src` par exemple) pour que le build se passe bien. 

Pour info, le problème n'est pas présent si on build avec `babel`

Merci et je suis dispo pour des précisions

**Comment by Tumulte** [comment]
Je ferme le ticket parce que je n'arrive pas a reproduire le problème sur stackblitz.... en tout cas il y a une configuration où le index.ts pose problème si il est à la racine. 

dans le cas où quelqu'un remonterait des erreurs TS liés au module aide-vélo tu auras la solution

**Comment by mquandalle** [comment]
Je vais retirer le `index.ts` du paquet publié
