### ISSUE TITLE
Complément pour Communauté de commune Grand lieu communauté

### ISSUE THREAD

**Issue by CorentinLemaitre** [mquandalle/mesaidesvelo#225]
Tout d'abord bravo à tous les contributeurs pour le travail accompli ! 👏 

En consultant la liste des aides, il y a une aide à l'achat qui n'est pas encore référencé sur le site pour les habitants de la CC Grand Lieu Communauté (Siren : 244400438). 

Voici les aides : 
- Pour l'achat d'un vélo mécanique : 50 €
- Pour l'achat d'un vélo à assistance électrique, d'un kit d'électrification ou d'un vélo pliant : 100 €
- Pour l'achat d'un vélo cargo ou adapté PMR : 300 €
- Pour la réparation d'un vélo ! prise en charge jusqu'à 50 € HT sur le montant de la facture (réparation mécanique uniquement effectuées chez l'un des [réparateurs du territoire](https://www.grandlieu.fr/node/4283))

Source : [site web grand lieu communauté](https://www.grandlieu.fr/vivre-et-habiter/mobilite/velo/operation-tous-velo).

**Comment by mquandalle** [comment]
Merci pour l'info, corrigé dans #5445702
