### ISSUE TITLE
Mise à jour des subventions IDFM

### ISSUE THREAD

**Issue by coooly** [mquandalle/mesaidesvelo#227]
Hello,

IDFM a mis à jour ses subventions : https://www.iledefrance-mobilites.fr/le-reseau/services-de-mobilite/velo/prime-achat-velo

ça devient cumulable sans plafond (VAE ma ville 100 + IDFM 500 = 600€) mais limité à 50% du prix du vélo.

Nouvelles catégories:
- Velos Mécaniques pour les 15-25 ans 100€
- Electrification vélo 200€
Nouveauté quelque soit la catégorie :
- Les vélos reconditionnés ou d’occasion, vendus par des professionnels aussi éligibles

**Comment by mquandalle** [comment]
Merci pour l'info, corrigé dans #5445702
