### ISSUE TITLE
Ajout de l'aide de la CC de la Région de Molsheim-Mutzig

### ISSUE THREAD

**Issue by guillett** [mquandalle/mesaidesvelo#228]
https://www.cc-molsheim-mutzig.fr/velos-a-assistance-electrique.htm
https://www.banatic.interieur.gouv.fr/V5/recherche-de-groupements/fiche-rs-simple.php?siren=246701064&com=216703009

**Comment by mquandalle** [comment]
Merci Thomas ! J'ai intégré l'aide dans la [v3.0.11].(https://github.com/mquandalle/mesaidesvelo/blob/master/package-aides-velo/CHANGELOG.md#v3011---01062023)
