### ISSUE TITLE
Créer un logo

### ISSUE THREAD

**Issue by laem** [mquandalle/mesaidesvelo#236]
Ce serait bien je pense, pour mieux identifier le site. 

Une idée : billet de banque + vélo imprimé dessus. 

![mesaidesvelo](https://github.com/mquandalle/mesaidesvelo/assets/1177762/71480b0b-801f-407d-84d6-cd51d7909a18)

**Comment by laem** [comment]
![mesaidesvelo](https://github.com/mquandalle/mesaidesvelo/assets/1177762/7bc28eed-340d-44bc-a6d6-50fa9d00cc07)

Ça ressemble un peu trop à une gomme là.

**Comment by mquandalle** [comment]
Dalle3: vélo propulsé par des billets de banque 

![image](https://github.com/mquandalle/mesaidesvelo/assets/1730702/a8b1afbc-dd09-4b7f-a378-1f8b56c91615)

**Comment by laem** [comment]
Excellent, ça fait un peu "j'ai un vélo de riche qui balance des billets à la foule"

**Comment by laem** [comment]
![image](https://github.com/mquandalle/mesaidesvelo/assets/1177762/0eda62d3-5163-46cb-8ca0-7bbd6e08b73b)

flat icon of a light green bank note with a bike printed inside

**Comment by mquandalle** [comment]
Pas mal le premier billet ! Je ne sais pas si tu connais mais j'ai déjà utilisé https://vectorizer.ai pour transformer une image dall-e en svg et ça fonctionne bien.

**Comment by laem** [comment]
Ah merci beaucoup, je me demandais justement si ça existait.
