### ISSUE TITLE
Code insee Linselles 

### ISSUE THREAD

**Issue by baptou12** [mquandalle/mesaidesvelo#237]
Bonjour @mquandalle, 
en faisant la mise à jour du package coté aides-jeunes, je me suis rendu compte que le code insee de la commune de Linselles n'était pas bon a priori. 
En effet il fait référence à la commune de Ligny-en-Cambrésis.

Il faudrait remplacer ce code 59349 par 59352 si je ne me trompe pas. 

Disponible pour tout complément d'information.

**Comment by mquandalle** [comment]
Bonjour Baptise, c'est corrigé merci.
Je vais ajouter des tests pour contrôler automatiquement le code insee, vu que c'est une donnée que je rentre à la main pour l'instant.
