### ISSUE TITLE
Màj du Bonus Vélo

### ISSUE THREAD

**Issue by yasmine-glitch** [mquandalle/mesaidesvelo#243]
Mette à jour de la description : "Nouveau bonus $vélo applicable du 15 août 2022 au 31 décembre 2023."

Mettre à jour la condition plafond du RFR pour bénéficier d'un vélo électrique, cargo ou pliant => "Votre [revenu fiscal de référence] par part est inférieur ou égal à 15 400 €"

https://www.service-public.fr/particuliers/vosdroits/F36828

**Comment by mquandalle** [comment]
Bonjour Yasmine, c'est fait (le plafond était déjà à jour c'était juste la date dans le texte à modifier)
