### ISSUE TITLE
Montant par défaut pour l'aide Ile de France à Paris

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#28]
Bonjour, merci pour votre travail très utile, mais je croisque pourParis il a une erreur avec une subvention de 5 euros par la région

**Comment by mathieutu** [comment]
Hello. 

Je me permets de compléter. 

Le calcul est (presque ? ) correct. Dans le cas d'un vélo à 1500 €, il y a 33%, soit 495 de Paris, et ensuite il y a 50% d'idf, mais avec un plafond de 500€ et auquel on enleve les aides déjà versées donc... 5 €. 

Par contre le problème est sur l'affichage du plafond. Les plafonds évoluent e' fonctions des nombres indiqués, ce qui n'est pas normal. 

 
![Screenshot_20211115_232502_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/11351322/141862585-e0005753-7a74-4a6f-a61a-18e7a32d47aa.jpg)

**Comment by mquandalle** [comment]
Oui, le calcul par défaut est fait pour un vélo à 1500€, c'est complètement arbitraire et ça prête à confusion.

Une solution possible est de compter le vélo le plus cher possible, afin d'afficher la prime maximale au niveau de Paris, et cacher la prime Ile-De-France. La répartition entre les deux ne s'afficherait qu'une fois que l'utilisateur aura saisi le prix de son vélo.
