### ISSUE TITLE
Permettre d'indiquer de nouvelles communes proposant des aides

### ISSUE THREAD

**Issue by LeryJ** [mquandalle/mesaidesvelo#3]
De plus en plus de collectivités vont s'y mettre. Elles pourront référencer leurs aides directement.

**Comment by mquandalle** [comment]
Dans un premier temps je voulais faire un mini formulaire de retour utilisateur qui ouvre directement un ticket sur Github, un peu comme sur https://github.com/datagir/nosgestesclimat/issues/created_by/publicodes

**Comment by mquandalle** [comment]
J'ai ajouté un bouton de retour utilisateur ainsi qu'un Excel partagé
