### ISSUE TITLE
Problème avec l'affichage des plafonds

### ISSUE THREAD

**Issue by mathieutu** [mquandalle/mesaidesvelo#31]
Hello, vraiment cool ton site.
Super initiative, et ça me permet de découvrir publicodes dont je n'avais jamais entendu parler.

Je constate un problème au niveau de l'affichage des plafonds.  En effet ils évoluent en fonction de l'input utilisateur. Je pense que c'est volontaire, pour prendre en compte les aides déjà versées, mais pour les coup c'est confusant et on ne comprend pas bien pourquoi (ça mène d'ailleurs à des issues comme #28). 

Je pense qu'il vaut mieux mettre le vrai plafond et modifier uniquement le montant de l'aide. 

Quelques screens :
![Screenshot_20211115_233905_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/11351322/141864418-fdb6ba84-fe94-400e-ad4b-384bb2a2ecdc.jpg)

![Screenshot_20211115_233924_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/11351322/141864433-66ba952d-ecb9-4659-a08c-2ee90848fd9b.jpg)

Où un plus compliqué :
 ![Screenshot_20211115_232502_org.mozilla.firefox.jpg](https://user-images.githubusercontent.com/11351322/141864708-7c55514b-e768-49fb-9b0c-f4aea13c8a75.jpg)

 Je vais fouiller un peu dans le code pour essayer de comprendre d'où ça vient. 

👋

**Comment by mquandalle** [comment]
Effectivement, ça prête à confusion. C'est plus un effet de bord de l'implémentation qu'une véritable volonté ;)

Pour le coup ce n'est pas la partie la plus triviale du code, en gros on prend une sous règle de publicodes, l'attribut plafond, et on l'évalue dans le contexte courant [code](https://github.com/mquandalle/mesaidesvelo/blob/3e628f1e8adfcea683b66ecd5c98f6d04ba41a4a/src/lib/components/Details.svelte#L38). Je vais voir comment implémenter ça autrement.

PS: C'est darkreader sur Firefox android les screenshots ? ou une autre extension ?

**Comment by mathieutu** [comment]
Effectivement je viens de me taper la doc de publicodes et je comprends maintenant comment ça marche avec les `abattement`, et les `velo.prix`.

(j'en reviens pas du boulot qu'il y a la dessus, je suis encore en train de digérer et de réfléchir si et comment ça peut me servir. C'est juste peu user friendly, vu que les clefs et mecanismes sont des strings donc tout se mélange) 

Effectivement je pense qu' une valeur fixe pour le plafond (en tout cas dans la description) sera mieux.

Ps: Tout à fait. Je m'en rends même plus compte vu qu'il passe tout seul avec le tel et les défauts sont généralement pas mauvais avec Tailwind/Windy.
