### ISSUE TITLE
Aide achat vélo électrique à Marseille ? 

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#36]
Dans ma localisation (13001), je peux bénéficier d'aides uniquement pour un vélo électrique. Est-ce la réalité des aides étatiques et locales des Bouches du Rhône ou est-ce un oubli d'une autre aide aux vélos non électriques ..?

**Comment by mquandalle** [comment]
C'est bien le cas, les aides portent uniquement sur les vélos électrique.

On pourrait clarifier ce point dans l'interface avec un « pas de subvention pour un vélo mécanique classique », mais ça nécessite comme prérequis d'être quasi exhaustif sur les aides, afin de ne pas afficher cette mention indûment.
