### ISSUE TITLE
Les villes homonymes paratagent la même URL

### ISSUE THREAD

**Issue by mquandalle** [mquandalle/mesaidesvelo#50]
Par exemple il y a plusieurs villes qui s'appellent Massy mais une URL correspondant https://mesaidesvelo.fr/ville/massy, ce qui fait que le partage d'URL est cassé.

À voir comment gérer ces cas. J'aime bien la simplicité des URL comme `/ville/paris` que l'on peut rentrer à la main, peut-être ajouter le code INSEE seulement quand c'est nécessaire ? Ou bien systématiquement ?

**Comment by jmquandalle** [comment]
Plutot que le Code INSEE que personne ne connait, il est préférable de mettre n° de département (si suffisant) ou Code postal sinon

**Comment by fgaroby** [comment]
Je partage l'avis de @jmquandalle : une URL de type `/ville/91-Massy` résoudrait le problème, tout en étant facile à saisir et comprendre pour un néophyte.
Idéalement, il faudrait conserver les URL `/ville/Caen` (sans numéro de département, donc), à la fois pour des raisons de rétro-compatibilité et pour des raisons de simplification (on peut chercher une commune, sans forcément connaître le numéro de son département, si on n'y habite pas).
Dans le cas des villes homonymes comme Massy, cette URL afficherait la liste des villes homonymes, avec le bon lien vers chacune.

**Comment by mquandalle** [comment]
J'ai vérifié dans les données et effectivement mettre uniquement le code postal suffit à lever l’ambiguïté, il n'y a pas 2 villes homonymes dans le même département, ouf !
