### ISSUE TITLE
Superposition de l'auto-complétion de Google Chrome

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#52]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ :

J'ai toujours l'autocomplete de Chrome qui se met au-dessus de l'autocomplete de l'appli

Le champ d'input est : 

```html
<input type="text" class=" input autocomplete-input svelte-11pubrl" id="localisation-input" autocomplete="some-other-text" placeholder="Commune ou Code postal">
```

si on remplace "some-other-text" par "off" ça fonctionne pour moi, l'autocomplete de chrome n'apparait plus

**Comment by mquandalle** [comment]
C'est un problème avec le composant `<Autocomplete />` que nous utilisons. Une correction a été proposée sur : https://github.com/pstanoev/simple-svelte-autocomplete/pull/121

En soit le composant est constitué d'un unique fichier donc on pourrait aussi l'intégrer directement et le modifier pour mieux répondre aux besoins de l'application. À voir si la PR est mergée rapidement.
