### ISSUE TITLE
Code postal de Aÿ-champagne

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#56]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/ay-champagne :

Bonjour il y a une erreur sur code postal de la ville de AY-CHAMPAGNE, ce n'est pas 51150 mais 51160. Cordialement.

**Comment by mquandalle** [comment]
Dans le fichier publié par Etalab Aÿ-Champagne a deux codes postaux :
https://unpkg.com/@etalab/decoupage-administratif@0.9.0-0/data/communes.json

Comment savoir lequel utiliser ?
