### ISSUE TITLE
Retour sur ville/barlieu

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#59]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/barlieu :

La prime à la conversion pour l'achat d'un VAE n'est pas prise en compte.

Cdlt,

**Comment by mquandalle** [comment]
Je ne trouve rien sur le site https://www.barlieu.fr

Mais en fait il semble que le message concerne la prime à la conversion, je ferme en faveur de #41.
