### ISSUE TITLE
Kit de motorisations à intégrer

### ISSUE THREAD

**Issue by mquandalle** [mquandalle/mesaidesvelo#70]
Retour utilisateur : 

> C'est super !  :+1: 
> 
> Il restera à ajouter  les subventions pour les "kits de transformation electrique"
> 
> -    Paris: https://www.paris.fr/pages/lutte-contre-la-pollution-les-aides-a-la-mobilite-5373
> -    Vaucresson: http://www.vaucresson.fr/Mobilites.aspx
> -    courbevoie: https://www.ville-courbevoie.fr/1844/subvention-pour-l-achat-d-un-velo-electrique.htm

**Comment by pli01** [comment]
Salut,
Je complète ici les villes offrant une subvention pour les "kits de transformation electrique":

* Bordeaux: https://sedeplacer.bordeaux-metropole.fr/Velo/Pratique/Aide-a-l-achat-de-velo
* Toulon Provence Mediterannee: https://metropoletpm.fr/velo-assistance-electrique
