### ISSUE TITLE
Retour sur ville/paris

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#72]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/paris :

Les aides de Paris et de la région Île de France sont pour les vélos NEUFS uniquement. Ce serait utile de l'indiquer.

Dans mon cas, je fais du vélo en partie par engagement écologique, donc je vais acheter un vélo d'occasion pour économiser des ressources. Les aides ne me concernent donc pas.

Super site, merci ♥️

**Comment by mquandalle** [comment]
Merci pour le retour, je ferme en faveur de #85
