### ISSUE TITLE
Retour sur ville/landerneau

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#74]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/landerneau :

Bonjour,
Je constate une erreur ou alors je comprends mal… votre site m’annonce que je peux bénéficier d’une offre de l’Etat, alors que je ne vois aucune aide locale.
Or si je comprends bien l’aide d’Etat est versé à la condition soumise qu’une aide locale soit attribuée non ?

**Comment by mquandalle** [comment]
Les aides de l'État pour les vélos cargo ne nécessitent pas qu'une aide locale ait été attribuée.
