### ISSUE TITLE
Code postal Mauguio-Carnon

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#75]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ :

Bonjour et merci pour cette appli :)
Habitant la commune de Mauguio-Carnon ( 34130) celle-ci ne figure pas à son bon code postal mais celui de la Grande Motte .
Dès que vous aurez modifié, je passerai votre information sur notre site internet https://velopaysdelor.org ainsi que sur notre page fb et groupe velotaf.
Evelyne Scappaticci

**Comment by mquandalle** [comment]
Connexe #56
