### ISSUE TITLE
Retour sur ville/change-53

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#77]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/ville/change-53 :

Bonjour,
et merci pour cette super initiative ! Je viens de faire le test pour ma commune (53810 Changé), le résultat est correct (me semble-t'il) mais l'agglo est celle de Laval et non du choletais comme cela est indiqué. Cela dit le lien vers Laval Agglo est bon.
Est-il possible d'inclure dans la grille de calcul la prime à la casse qui donne droit à une somme conséquente pour l'achat d'un VAE ?
Bonne suite à vous !!!!
Bien cordialement
Guillaume

**Comment by mquandalle** [comment]
Pour la prime à la casse, voir #41
