### ISSUE TITLE
Ajouter Figeac

### ISSUE THREAD

**Issue by utilisateur-mav** [mquandalle/mesaidesvelo#78]
> Retour utilisateur effectué sur la page https://mesaidesvelo.fr/a-propos :

Bravo pour l'outil !
Une aide complémentaire sur la commune de Figeac : https://ville-figeac.fr/tourisme-et-environnement/environnement/environnement-actualite/1021-aide-a-l-acquisition-d-un-velo-a-assistance-electrique-pour-les-habitants-de-figeac

Pour éviter un travail conséquent de mise à jour, je vous suggère de proposer aux collectivités ou associations locales membres de la FUB de saisir les données nécessaires dans un formulaire spécifique.

**Comment by mquandalle** [comment]
Bonne remarque sur la saisie des données par les collectivités et associations, voir #69
